import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { MyThemeContextProvider } from "@/context/theme-context";
import Providers from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyThemeContextProvider>
      <html lang="en">
        <body className={cn('bg-neutral-100 dark:bg-gray-900 scroll-smooth', inter.className)}>
          <Providers>
            <div>
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </MyThemeContextProvider>
  );
}
